// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	GetAllUsers(ctx context.Context, organizationID string) ([]GetAllUsersRow, error)
	GetAllWebhooks(ctx context.Context, organizationID string) ([]GetAllWebhooksRow, error)
	GetOrganization(ctx context.Context, id string) (GetOrganizationRow, error)
	GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (GetWebhookRow, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationAvatar(ctx context.Context, arg UpdateOrganizationAvatarParams) error
	UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWebhookRetryPolicy(ctx context.Context, arg UpdateWebhookRetryPolicyParams) error
	UpdateWebhookSecret(ctx context.Context, arg UpdateWebhookSecretParams) error
	UpdateWebhookStatus(ctx context.Context, arg UpdateWebhookStatusParams) error
}

var _ Querier = (*Queries)(nil)
